export const cities = [
  "New York, NY",
  "Los Angeles, CA",
  "Chicago, IL",
  "Houston, TX",
  "Phoenix, AZ",
  "Philadelphia, PA",
  "San Antonio, TX",
  "San Diego, CA",
  "Dallas, TX",
  "San Jose, CA",
  "Austin, TX",
  "Jacksonville, FL",
  "San Francisco, CA",
  "Columbus, OH",
  "Indianapolis, IN",
  "Charlotte, NC",
  "Seattle, WA",
  "Denver, CO",
  "Washington, DC",
  "Boston, MA",
  "El Paso, TX",
  "Nashville, TN",
  "Detroit, MI",
  "Memphis, TN",
  "Portland, OR",
  "Oklahoma City, OK",
  "Las Vegas, NV",
  "Louisville, KY",
  "Baltimore, MD",
  "Milwaukee, WI",
  "Albuquerque, NM",
  "Tucson, AZ",
  "Fresno, CA",
  "Sacramento, CA",
  "Kansas City, MO",
  "Mesa, AZ",
  "Atlanta, GA",
  "Colorado Springs, CO",
  "Virginia Beach, VA",
  "Raleigh, NC",
  "Omaha, NE",
  "Miami, FL",
  "Cleveland, OH",
  "Tulsa, OK",
  "Oakland, CA",
  "Minneapolis, MN",
  "Wichita, KS",
  "Arlington, TX",
  "New Orleans, LA",
  "Tampa, FL",
];
